name: Deploy to GitHub Pages


on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [14.x]


    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run generate
      - name: Add .nojekyll file
        run: touch ./.output/public/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: website
          folder: .output/public
